In [1]:
from sklearn.datasets import load_breast_cancer as lbc
import torch
import numpy as np

import torch.nn.functional as F
from torch.optim import Adam
from models import *
from tqdm import tqdm
import matplotlib.pyplot as plt
import training_utils as utils

%load_ext autoreload
%autoreload 2

device = torch.device("cpu")

In [2]:
X, y = lbc(return_X_y=True)
X = torch.tensor(X)
y = torch.tensor(y)
data = utils.CustomDataObject(X, y)
data = torch.utils.data.DataLoader(data, batch_size=1)
print(X.shape)
print(y.shape)

torch.Size([569, 30])
torch.Size([569])


In [3]:
def categorical(y):
    N = len(y)
    M = np.max(y) + 1
    Y = np.zeros((N, M))
    for i in range(N):
        Y[i, y[i]] = 1
    return Y

In [11]:
def run_model(model, optimizer, train_loader, device, num_epochs=30):
    # pbar = tqdm(range(num_epochs))
    for i in range(num_epochs):
        for bi, (x, y) in enumerate(train_loader):
            optimizer.zero_grad()
            x, y = x.to(device), y.to(device)
            out, kl = model(x)
            print(out)
            out = F.softmax(out, dim=1)
            print(out)
            
            
            loss = F.nll_loss(out, y)
            loss.backward()
            optimizer.step()
        print(f"epoch: i, loss: {loss}")
        exit()
        # pbar.set_description(f"{loss}")

In [5]:
model = BayesianFC(X.shape[1], 2, [20, 20])
optim = Adam(model.parameters(), lr=0.001)

In [12]:
run_model(model, optim, data, device)

tensor([[1., 0.]], dtype=torch.float64, grad_fn=<SoftmaxBackward>)
tensor([[0., 1.]], dtype=torch.float64, grad_fn=<SoftmaxBackward>)
tensor([[1., 0.]], dtype=torch.float64, grad_fn=<SoftmaxBackward>)
tensor([[1.0000e+00, 1.5961e-53]], dtype=torch.float64,
       grad_fn=<SoftmaxBackward>)
tensor([[0., 1.]], dtype=torch.float64, grad_fn=<SoftmaxBackward>)
tensor([[0., 1.]], dtype=torch.float64, grad_fn=<SoftmaxBackward>)
tensor([[0., 1.]], dtype=torch.float64, grad_fn=<SoftmaxBackward>)
tensor([[0., 1.]], dtype=torch.float64, grad_fn=<SoftmaxBackward>)
tensor([[0., 1.]], dtype=torch.float64, grad_fn=<SoftmaxBackward>)
tensor([[0., 1.]], dtype=torch.float64, grad_fn=<SoftmaxBackward>)
tensor([[0., 1.]], dtype=torch.float64, grad_fn=<SoftmaxBackward>)
tensor([[1., 0.]], dtype=torch.float64, grad_fn=<SoftmaxBackward>)
tensor([[0., 1.]], dtype=torch.float64, grad_fn=<SoftmaxBackward>)
tensor([[1., 0.]], dtype=torch.float64, grad_fn=<SoftmaxBackward>)
tensor([[0., 1.]], dtype=torch.float64,

KeyboardInterrupt: 